id: AFEABA0E5
title: A Dzogchen Tögal Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:12:02.592746
  last_modified_at: 2022-02-28 23:12:02.592753
